### ISSUE TITLE
Hold position command doesn't work properly

### ISSUE THREAD

**Issue by O-d-i-n-n** [mrsterner/GuardVillagers#11]
**Describe the bug**
Crossbow villagers don't remain in place after you command them to hold position.

**To Reproduce**
1. Obtain the Hero of the Village effect.
2. Open any crossbowman villager's inventory.
3. Remove the cross from the hold position button.
4. Close the villager's inventory.
5. Observe the villager continuing to walk around (or chase enemies if they are present) as if the command was not given.

**Expected behavior**
The villager stays in place and doesn't move from their position.

**Mod Verion**
guard-villagers-fabric-1.18.2-1.0.10

**Additional context**
[guard-villagers-fabric-1.18.2-1.0.10](https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric/files/3697634)

**Comment by mrsterner** [comment]
Very low priority

**Comment by xzuyn** [comment]
why would that be low priority, its one of the few things the mod adds.

**Comment by GrievouslyGreaves** [comment]
I'm using the fabric version for 1.19.1 and the hold position feature still doesn't work. I don't understand why it's considered low priority but considering its one of two commands you'd think it'd be a pretty high priority

**Comment by O-d-i-n-n** [comment]
1.19.3 still doesn't work:(

**Comment by mrsterner** [comment]
fixed in 1.1.0
