### ISSUE TITLE
Mod crash after click the option

### ISSUE THREAD

**Issue by Narnilz** [mrsterner/GuardVillagers#117]

**Comment by Poopooracoocoo** [comment]
No crash report or log?

**Comment by Narnilz** [comment]
The game crashed whilst mouseclicked event handler
Error: java.lang.IllegalAccessError: class net.minecraft.class_429 tried to access private method 'void net.minecraft.class_2960.<init>(java.lang.String, java.lang.String)' (net.minecraft.class_429 and net.minecraft.class_2960 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6591f517)
 Exit Code -1

**Comment by Poopooracoocoo** [comment]
I think a full crash report or log might be more helpful or at least reproducible. You can find crash reports in the crash-reports folder and logs in the logs folder in .minecraft. The newest log will be called "latest".
