### ISSUE TITLE
UPDATE 2.1.1-1.21 found in 1.20.1 Minecraft

### ISSUE THREAD

**Issue by Ramenboodles** [mrsterner/GuardVillagers#120]
Playing on Minecraft 1.20.1 and decided to update the mod, turns out the update 2.1.1-1.21.jar is for Minecraft 1.21 but listed as 1.20.1

Just a heads up. Also, would expect an update for 1.20.1 for the arrow crash?

thx

**Comment by mrsterner** [comment]
i dont know what the "arrow crash" is

**Comment by Collier21** [comment]
so if im using 1.21 i need to download the 1.21.1 version of the mod?
