### ISSUE TITLE
Game crashes when giving villager a weapon.

### ISSUE THREAD

**Issue by omeggga** [mrsterner/GuardVillagers#16]
Upon trying to give villagers a weapon the game freezes and crashes entirely. It should be noted that I have "giveGuardStuffHOTV" set to false.

Should also be noted that this happens on version 1.0.11 while the older 1.0.10 seems fine.

Crash file:
[crash-2022-04-19_21.51.33-client.txt](https://github.com/mrsterner/GuardVillagers/files/8517083/crash-2022-04-19_21.51.33-client.txt)

**Comment by mrsterner** [comment]
Cannot reproduce, if the issue persists in v14, open again
