### ISSUE TITLE
Guard Villagers Crashes Game When Loading in Village

### ISSUE THREAD

**Issue by natsudragneelthefiredragon** [mrsterner/GuardVillagers#17]
**Describe the bug**
Game crashes when a village is loaded in, I didn't even see it

**To Reproduce**
1. Find a village or accidentally find a village

**Expected behavior**
Not to crash

**Screenshots**
N/A

**Mod Version**
1.18.1-1.0.11

**Additional context**
I believe it may be crashing because of me using 1.18.2,
Usually mods work if on the same major version,
Did this change with 1.18.2?

Also here is the log:
https://paste.ee/p/0qYV6#lLSTnAcNjKIQUVGVSavAytFCemYc7vd8

**Comment by mrsterner** [comment]
1.18.2 doesnt work with 1.18.1 and vise versa
