### ISSUE TITLE
Game crash for unknown reason (in modpack)

### ISSUE THREAD

**Issue by Rad233** [mrsterner/GuardVillagers#18]
**Describe the bug**
I don't know exactly, I was just hanging around the village. 
**To Reproduce**
1. create the world
2. hang around the village
3. 
4. 

**Expected behavior**
I installed other mods related to shield and arrow, but I really couldn't make sure what's causing the crash...
**Screenshots**
![image](https://user-images.githubusercontent.com/99306685/164981163-06d5899c-9ad9-4ac1-a250-41fc5e19f00d.png)

**Mod Verion**
Which version of the mod are you using?
1.18.1-1.0.11
**Additional context**
[crash-2022-04-24_22.15.27-server.txt](https://github.com/mrsterner/GuardVillagers/files/8549875/crash-2022-04-24_22.15.27-server.txt)

**Comment by mrsterner** [comment]
copy of #14
