### ISSUE TITLE
3 way mod conflict between inspecio, REI and this mod

### ISSUE THREAD

**Issue by BossCreeper81** [mrsterner/GuardVillagers#2]
Game crashes when searching anything, while REI, guard villagers and Inspecio are installed.

1 .Install REI, Inspecio and Guard villagers (fabric)
2. Start the game
3. Crash

Disabling the search tooltip feature in REI "fixes" the bug

1.18.1
fabric

logs:
https://pastebin.com/xcPZP2si //only the 3 mods and their dependencies installed
https://crashy.net/43KxFDcVH6NL5g7QqqM2 // crashy with my full setup

Removing either inspecio or guard villagers also fixes the bug

[shedaniel/RoughlyEnoughItems#740]
[Queerbric/Inspecio#61]

Both of them say, this mod is causing the issue

**Comment by BossCreeper81** [comment]
Literally just removing ServerWorld from this line:

"dev.mrsterner.guardvillagers.common.entity.GuardEntity.writeCustomDataToNbt (GuardEntity.java:334)" 
[ -> this.readAngerFromNbt(this.world, nbt); ] 

fixes the issue in the outdates version on github.

readAngerFromNbt apparently doesnt need to cast to ServerWorld, like LambdaAurora said here: Queerbric/Inspecio#13

**Comment by mrsterner** [comment]
Done, will appear in next update
