### ISSUE TITLE
Game crashes upon starting up

### ISSUE THREAD

**Issue by omeggga** [mrsterner/GuardVillagers#21]
**Describe the bug**
The game crashes upon starting up with the latest version of the mod installed.

**To Reproduce**
1. Start the game.

**Expected behavior**
Game is supposed to launch.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/42063882/166572815-704decf4-8f6a-4391-a811-8ca3b5fa4928.png)

**Mod Version**
1.0.13

**Additional context**
fabric api version: 0.51.1
cloth version: 6.2.57

Crash logs below:
[crash-2022-05-03_23.46.37-client.txt](https://github.com/mrsterner/GuardVillagers/files/8614515/crash-2022-05-03_23.46.37-client.txt)
[crash-2022-05-03_23.49.48-client.txt](https://github.com/mrsterner/GuardVillagers/files/8614516/crash-2022-05-03_23.49.48-client.txt)
[crash-2022-05-03_23.51.20-client.txt](https://github.com/mrsterner/GuardVillagers/files/8614517/crash-2022-05-03_23.51.20-client.txt)
[crash-2022-05-03_23.52.06-client.txt](https://github.com/mrsterner/GuardVillagers/files/8614518/crash-2022-05-03_23.52.06-client.txt)
[crash-2022-05-03_23.53.55-client.txt](https://github.com/mrsterner/GuardVillagers/files/8614519/crash-2022-05-03_23.53.55-client.txt)

**Comment by mrsterner** [comment]
fixed in v14
