### ISSUE TITLE
Unable to Make Guard Villagers

### ISSUE THREAD

**Issue by StealthMeister1** [mrsterner/GuardVillagers#22]
**Describe the bug**
Can't make guard villagers.

**To Reproduce**
1. No Idea
2. No Idea
3. No Idea
4. No Idea

**Expected behavior**
Make guard villagers.

**Screenshots**
N/A

**Mod Verion**
1.18.2.1.4.1

**Additional context**
Tried using the iron sword/crossbow to make guard villagers. Didn't work. Made sure I crouched, faced them completely, used the HOTV effect, the villager was unemployed, and the villager was naturally spawned. I spawned my own just to make sure and it didn't act any differently. Idk what to do.

**Comment by StealthMeister1** [comment]
Would appreciate some actual assistance.

**Comment by HenrikoMagnifico** [comment]
It seems the mod isn't loading for me either! It seems like the startup log doesn't mention the mod either, any help would be very much appreciated!
