### ISSUE TITLE
seems like you've opt out on third party usage of the mod on Curseforge

### ISSUE THREAD

**Issue by FederAndInk** [mrsterner/GuardVillagers#23]
Because of your decision to opting out to "allow the distribution of this project outside the curseforge-overwolf ecosystem", now cf is starting enforcing that stuff, so your mod is effectively undownloadable from third party launchers and many modpacks broke because of your mod

**Comment by FederAndInk** [comment]
Third party launchers such as MultiMC, PolyMC, GDLauncher, ... this is especially annoying on Linux as curseforge for MC is not on Linux.
Just to let you know

**Comment by DDriggs00** [comment]
Requesting re-open. This is a relatively severe bug that can be fixed by correcting the misconfigured setting.

**Comment by DDriggs00** [comment]
For more details on how this negatively impacts both players and developers, see here: https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric/download/3779559
