### ISSUE TITLE
Game Crashes at Launch

### ISSUE THREAD

**Issue by GreyGoldFish** [mrsterner/GuardVillagers#39]
The game crashes at launch, and it's a conflict between one of my mods, as removing GuardVillagers lets the game run as normal.

`Caused by: java.lang.VerifyError: Bad access to protected data in invokevirtual`

I've attached the crash report below.

[crash-2022-11-18_12.25.21-client.txt](https://github.com/mrsterner/GuardVillagers/files/10042552/crash-2022-11-18_12.25.21-client.txt)

**Comment by hypyx** [comment]
Not entirely sure if this will help you, but I had issues with the fabric 1.19.2 version where after clicking play, nothing happened (minecraft still (apparently) running albeit no interface).

Tried the 1.19.1 version and all seems to work as expected (so far)...
