### ISSUE TITLE
Guard functions not working

### ISSUE THREAD

**Issue by naurpy** [mrsterner/GuardVillagers#41]
I don't know if anyone else is having this problem but I added this mod to my server and I had hero of the village. But I couldn't make the guard villager follow me or make it stay in place, It just wouldn't function. And I tested it in single player and it worked out fine, and now I'm wondering how do I fix this?

**Comment by Eugene697** [comment]
I have the same issue. Cannot get these guards to do anything but wander around

**Comment by mrsterner** [comment]
fixed in 1.1.0
