### ISSUE TITLE
[{Fabric/Quilt} 1.19] - Could not execute encryption stage 'main' due to errors, provided by *Guard Villagers*

### ISSUE THREAD

**Issue by mettlephaontoms** [mrsterner/GuardVillagers#45]
I installed this mod along with the Simply Optimized mod pack and have customized it, removing a few unnecessary mods and adding more compatible mods to enhance the vanilla experience as i see fit. I hoped that the latest release would have resolved this issue however my case seems to be unique, i tried versions 1.19.2 and 1.19.3 and my game fails to launch without giving notice. I had to either look at task manager and monitor Java or restart the launcher after waiting for a time to see that it failed.

The mods that i've added to this profile are the following:
XaerosWorldMap
Void Fog
villagerconfig
tweakeroo
takesapillage
snowday
shulkerboxtooltip
powershot
peepingcreepers
no-telemetry
nofog
no-enchant-cap
NoChatReports
malilib
minelib
inventorytabs
fireworkfrenzy
fabric-carpet
freecam
entity-view-distance
darkness-fabric
Command-Macros-Mod
Chunky
bedrock-miner
armorpointsapp
AmbientSounds
WorldEdit

My latest additions are Impaled and trulytreasures.

**Comment by mettlephaontoms** [comment]
Turns out other people have this issue after reading a relatively new post going more in-depth into it, does that mean this post will be removed for redundancy?

**Comment by mrsterner** [comment]
fixed in 1.0.18
