### ISSUE TITLE
Unable to give guard villagers any equipment.

### ISSUE THREAD

**Issue by omeggga** [mrsterner/GuardVillagers#52]
Upon right clicking a guard villager, regardless of whether "giveGuardStuffHOTV" is true or false, the window to give guard villagers gear will not display, thus the guard villager will not e able to have their inventory modified by the player.

**Comment by Dannydads** [comment]
I was able to give them swords/crossbows only after I got Hero of the Village

**Comment by wackoamd1** [comment]
yes i have the same problem on my server , no matter these setting
   "giveGuardStuffHOTV": false,
    "setGuardPatrolHotv": false,
    "ConvertVillagerIfHaveHOTV": false,

u just cant give them anything or interact with them. 
which sucks cause patrols and raids are off at the server
