### ISSUE TITLE
 Clerics do not heal injured villagers/guards; smiths do not repair iron golems after saving and reloading (Issue not resolved)

### ISSUE THREAD

**Issue by omeggga** [mrsterner/GuardVillagers#53]
Title. To reproduce this issue make a cleric and/or a smith.

If testing a cleric, spawn a villager near the cleric then injure the newly-spawned villager until the cleric interevenes. Once he's finished healing, save and quit, then rejoin the world. Injure the villager once again to near-death conditions, the cleric is supposed to heal the villager but does not.

If tesing a smith, spawn a golem near the smith then injure the newly-spawned golem until the smith interevenes. Once he's finished healing, save and quit, then rejoin the world. Injure the golem once again to near-death conditions, the smith is supposed to heal the golem but does not.

This issue persists, it is not resolved at all despite your closure.

**Comment by O-d-i-n-n** [comment]
Not sure if this is connected, but one of my armorers randomly stopped fixing the guars' armor. No idea why and when this happened.

**Comment by rinamasahiro** [comment]
I'm playing BetterMC modpack and am having the same issue. Neither the weaponsmith nor the toolsmith are healing the Guards golem. Is this configured somewhere?

**Comment by rinamasahiro** [comment]
Updated to 1.1.2 and have been in the village for several in-game days, with the injured golem trapped in the same area as the three blacksmiths. Despite the optimistic "fixed everything" changelog note, this bug has, unfortunately, not been fixed, and my poor golem remains injured...

What I did notice is that the config is no longer particularly human-readable, although at least it doesn't ask for you to restart the game when you turn off the hotv requirement.

**Comment by rinamasahiro** [comment]
Today's experiment was "recreation of the issue with a new instance where this mod and dependencies are the only things installed".

Exactly as described before, villagers who are saved with the world do not resume the custom AI behaviors when the world is reloaded.

Minecraft 1.19.2
Fabric 0.14.19
Fabric API 0.76.0 
MidnightLib Fabric 1.0.0
Guard Villagers 1.1.2

**Comment by rinamasahiro** [comment]
> Not sure if this is connected, but one of my armorers randomly stopped fixing the guars' armor. No idea why and when this happened.

Further experiment in the single-mod world indicates that armorers don't fix armor and weaponsmiths don't fix weapons even if they would repair golems, so I don't think it's related to this issue and I'll open a new ticket if it's not already open.
