### ISSUE TITLE
MC 1.19.3 crash

### ISSUE THREAD

**Issue by PauloSobieGra** [mrsterner/GuardVillagers#55]
Hi!
Whenever I try to turn on my game, It always crashes. I have the latest version.
It crashes with, and without any other mods.
Here are the logs:
[crash-2023-01-24_03.01.22-client.txt](https://github.com/mrsterner/GuardVillagers/files/10485767/crash-2023-01-24_03.01.22-client.txt)

**Comment by omeggga** [comment]
The mod now uses midnightlib, install it and you should be good: https://www.curseforge.com/minecraft/mc-mods/midnightlib
