### ISSUE TITLE
MC 1.19.2 Crash

### ISSUE THREAD

**Issue by foyiho7307** [mrsterner/GuardVillagers#57]
Pretty much as the title suggests. I'm only using the 4 mods the Fabric launcher says I must use to launch the game but I still get an error. 

**Guard Villagers + MidnightLib, ClothConfig, FabricAPI Only**

[crash-2023-01-26_16.49.34-client.txt](https://github.com/mrsterner/GuardVillagers/files/10506189/crash-2023-01-26_16.49.34-client.txt)

**Comment by foyiho7307** [comment]
Forgot to include that I am just using these to isolate the issue, I have a bigger mod list I am using too but removed the others for now. I can include that crash log with all the other mods if you'd like.

**Comment by Chernosjk** [comment]
I am also experiencing the same issue in 1.19.2, with the same 4 mods loaded

[crash-2023-02-06_05.23.00-client.txt](https://github.com/mrsterner/GuardVillagers/files/10613872/crash-2023-02-06_05.23.00-client.txt)

**Comment by SplendidAlakey** [comment]
You are both missing [Architectury](https://www.curseforge.com/minecraft/mc-mods/architectury-api). I have no idea why it's not defined as a hard dependency, because it is.

**Comment by mrsterner** [comment]
fixed
