### ISSUE TITLE
Duping

### ISSUE THREAD

**Issue by rizelix** [mrsterner/GuardVillagers#58]
So you can pretty much dupe an item specifically the armor only
This is how it works:
1) Find a slot in one of their slots
![2023-01-26_13 56 18](https://user-images.githubusercontent.com/123619093/214768337-144824e1-cbba-4de2-bb0d-8e07a03a0a39.png)
2) Pick an item
![2023-01-26_13 56 19](https://user-images.githubusercontent.com/123619093/214768357-77db632e-42de-4429-8dac-1f970f41ee3b.png)
3) An armor should pop up and then replace the item to get the armor
![2023-01-26_13 56 24](https://user-images.githubusercontent.com/123619093/214768369-866ec146-9c8d-4de0-8ad1-4310c4134349.png)
4) Throw it out of your inventory
![2023-01-26_13 56 31](https://user-images.githubusercontent.com/123619093/214768377-e78bd350-b901-4285-8446-d751ec735cdd.png)
5) and look at this lol
![2023-01-26_13 56 43](https://user-images.githubusercontent.com/123619093/214768384-9d078d03-036a-4c3d-b972-cdbd19d33e87.png)
Thats pretty much it, pls fix this. Very good mod by the way! I like it.

**Comment by rizelix** [comment]
i think the last image was duped leggings instead of boots so my bad on that one btw!

**Comment by O-d-i-n-n** [comment]
Come here to report the same thing and saw your report. Really hope this gets fixed soon.

**Comment by O-d-i-n-n** [comment]
Btw how did you get the villager to put the shield on their back? Is that another mod you're using?

**Comment by rizelix** [comment]
im pretty sure i used a resource pack (Faithless) I dont think any mods would do it since all of the mods I used were either for fps boost, structure mods, and the villager one. If the villager didnt have the shield on their back then its def Faithless Resource pack.

**Comment by mrsterner** [comment]
Dont know whats causing it

**Comment by mrsterner** [comment]
jk i found the issue, fixed in 1.0.20
