### ISSUE TITLE
Village Guard Crash Bug Report

### ISSUE THREAD

**Issue by Gushko** [mrsterner/GuardVillagers#6]
Interacting with a guard while having hero of the village resulted in a crash.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2/5/22, 8:05 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_5601
	at dev.mrsterner.guardvillagers.GuardVillagersClient.<clinit>(GuardVillagersClient.java:51)
	at dev.mrsterner.guardvillagers.client.screen.GuardVillagerScreenHandler.<init>(GuardVillagerScreenHandler.java:36)
	at dev.mrsterner.guardvillagers.common.entity.GuardEntity$GuardScreenHandlerFactory.createMenu(GuardEntity.java:734)
	at net.minecraft.class_3222.method_17355(class_3222.java:1032)
	at dev.mrsterner.guardvillagers.common.entity.GuardEntity.openGui(GuardEntity.java:741)
	at dev.mrsterner.guardvillagers.common.entity.GuardEntity.method_5992(GuardEntity.java:708)
	at net.minecraft.class_1308.method_5688(class_1308.java:1130)
	at net.minecraft.class_1657.method_7287(class_1657.java:1059)
	at net.minecraft.class_3244$1.method_33897(class_3244.java:1318)
	at net.minecraft.class_3244$1.method_34219(class_3244.java:1329)
	at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116)
	at net.minecraft.class_2824.method_34209(class_2824.java:66)
	at net.minecraft.class_3244.method_12062(class_3244.java:1315)
	at net.minecraft.class_2824.method_12251(class_2824.java:53)
	at net.minecraft.class_2824.method_11054(class_2824.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756)
	at net.minecraft.class_1255.method_5383(class_1255.java:110)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5601
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 29 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 4.18.0-348.7.1.el8_5.x86_64
	Java Version: 17.0.1, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Red Hat, Inc.
	Memory: 1762659320 bytes (1681 MiB) / 3397386240 bytes (3240 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 106 Stepping 6
	Microarchitecture: Ice Lake (Server)
	Frequency (GHz): 2.60
	Number of physical packages: 2
	Number of physical CPUs: 56
	Number of logical CPUs: 112
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 585471.19
	Virtual memory used (MB): 614247.19
	Swap memory total (MB): 77823.99
	Swap memory used (MB): 7970.60
	JVM Flags: 20 total; -Xmx4096M -Xms2662M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.4.7
		ae2: Applied Energistics 2 10.0.0
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.1
		appleskin: AppleSkin 2.3.0+mc1.18.1
		arcanus: Arcanus 1.27
		architects_palette: Architect's Palette Fabric 1.3
		architectury: Architectury 3.6.15
		artifality: Artifality 0.5.4
		attributefix: AttributeFix 13.0.5
		balm-fabric: Balm 2.4.1+0
		bclib: BCLib 1.2.5
		beaconoverhaul: Beacon Overhaul 1.5.0+1.18
		bedspreads: Bedspreads 1.5.0-1.18
		betterend: Better End 1.0.1
		blockus: Blockus 2.3.4+1.18.1
		blue_endless_jankson: jankson 1.2.1
		capybara: Capybara 1.0.1
		cardinal-components-base: Cardinal Components API (base) 4.1.0
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.0
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		carrier: Carrier 1.9.1
		cavetweaks: Cave Tweaks 1.0
		chalk: Chalk 1.2.1
		chunky: Chunky 1.2.164
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		collective-fabric: Collective (Fabric) 3.14
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		comforts: Comforts 1.0.1-1.18.1
		connectiblechains: Connectible Chains 2.0.1+1.18.1
		couplings: Couplings 1.7.1+1.18
		craftingtweaks: Crafting Tweaks 13.0.0
		customstars: Custom Stars 0.7+1.18
		decorative_blocks: Decorative Blocks 2.0.4
		despawningeggshatch-fabric: Despawning Eggs Hatch (Fabric) 2.3
		direbats: Direbats 2.1.0
		dragonloot: DragonLoot 1.0.10
		dual_riders: DualRiders 1.0.5
		dusk: Dusk Mod 1.18-1.7
		fabric: Fabric API 0.46.3+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a83a
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.2+d7c144a83a
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a83a
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a83a
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a83a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.7+d7c144a83a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d953a
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf53a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a83a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a83a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.8+d7c144a83a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a83a
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.5+3ac43d953a
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.12+d7c144a83a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a83a
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.5+d7c144a83a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.10+b4f4f6cd3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a83a
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd3a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.3+d7c144a83a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.11+d7c144a83a
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac3a
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.1+d7c144a83a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a83a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d953a
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a83a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.13+d7c144a83a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a83a
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.2+d7c144a83a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.7+d7c144a83a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.7+fb3b57b43a
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.8+d7c144a83a
		fabricloader: Fabric Loader 0.12.12
		fallingtree: FallingTree 3.2.0b2
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		farsight: Farsight Mod 1.18-1.5
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 1.7.1
		forgeconfigapiport: Forge Config API Port 3.1.1
		geckolib3: Geckolib 3.0.32
		glassential: Glassential 1.3.0
		goosik-config: goosik-config 0.2.0
		guardvillagers: Guard Villagers Fabric 1.0.2
		harvest_scythes: Harvest Scythes 2.4.1
		iceberg: Iceberg 1.0.38
		imm_ptl_core: Immersive Portals Core 1.2.5
		immersive_portals: Immersive Portals 1.2.5
		incantationem: Incantationem 1.1.3+1.18.1
		infusion_table: Infusion Table 1.0.5
		ironchests: Iron Chests for Fabric 1.5.3
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kleeslabs: KleeSlabs 11.0.0
		konkrete: Konkrete 1.3.3
		kubejs: KubeJS 1801.4.2-build.296
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		levelz: LevelZ 1.1.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.7
		logprot: Logprot Mod 1.18-1.5
		lovely_snails: Lovely Snails 1.0.3+1.18
		lumiwool: Luminous Wool 1.2.2
		maybe-data: Maybe data 1.0.1-1.17
		me_hypherionmc_simple-rpc-common: simple-rpc-common 1.0.17
		megane: megane 7.0.2
		megane-api: megane-api 7.0.0
		megane-applied-energistics-2: megane-applied-energistics-2 7.0.1
		megane-fabric-transfer: megane-fabric-transfer 7.0.0
		megane-reborn-core: megane-reborn-core 7.0.0
		megane-reborn-energy: megane-reborn-energy 7.0.0
		megane-runtime: megane-runtime 7.0.0
		megane-tech-reborn: megane-tech-reborn 7.0.0
		megane-vanilla: megane-vanilla 7.0.0
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.6.1-MC1.18.1
		mousewheelie: Mouse Wheelie 1.8.0+mc1.18-pre5
		nears: Nears 1.1.2
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		oro_config: OroArmor Config 2.1.0
		owo: oωo 0.5.1+1.18
		oxidized: Oxidized 1.5.2
		paintings: Paintings++ 9.1.0.0
		patchouli: Patchouli 1.18.1-65-FABRIC
		phosphor: Phosphor 0.8.1
		pipe: Pipe 1.6.2
		polymorph: Polymorph 0.0.19-1.18.1
		publicguiannouncement: Public Gui Announcement 3.2.0.0
		q_misc_util: QMiscUtil 1.2.5
		quarryplus: QuarryPlus 18.2.0
		quartzelv: Quartz Elevator 2.1.0+1.18
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0-beta.8
		rhino: Rhino 1801.1.8-build.99
		rpgdifficulty: Rpg Difficulty 1.0.9
		seedfix: Seed Fix 1.0.0
		simple-rpc: Simple Rpc 2.7.1
		slimyfloor: Slimy Floor 1.18-1.2.2
		someforgepatchesported: Some Forge Patches Ported 1.0.2
		spark: spark 1.7.2
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		team_reborn_energy: Energy 2.1.0
		techreborn: Tech Reborn 5.1.0-beta.8
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0.12
		trinkets: Trinkets 3.1.0
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		twigs: Twigs 1.1.2
		waystones: Waystones 9.0.3
		wolveswitharmor: Wolves With Armor 1.7.0-1.18
		wthit: wthit 4.4.1
		xaeroworldmap: Xaero's World Map 1.20.1
		yigd: You're in Grave Danger 1.2.14
		yosbr: YOSBR 0.1.1
	Server Running: true
	Player Count: 1 / 1337; [class_3222['Gushko'/34, l='ServerWorld minecraft:overworld Valhelsia_Fabric_1627122', x=1781.44, y=66.50, z=585.23]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by mrsterner** [comment]
Fixed in latest release
