### ISSUE TITLE
Guard Villager error launch Minecraft

### ISSUE THREAD

**Issue by CaiZack** [mrsterner/GuardVillagers#60]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'guardvillagers'!
	at

Happens on my Mac machine (Zulu java 17)

[log.txt](https://github.com/mrsterner/GuardVillagers/files/10948050/log.txt)

**Comment by Dillo234** [comment]
I have the exact same prohblem when i try to start my server.
I added the latest log here:
 
https://drive.google.com/file/d/19L2BaqlmeW2i5fz3L1vdhkvg0FEJ5JQL/view?usp=sharing

The problem begins at line 111

**Comment by CaiZack** [comment]
Still don't know, I guess maybe the java environment? I am using Java 17

**Comment by CaiZack** [comment]
It seems need specific version of Architectury mod for my instance to launch successfully.
Architectury 6.4.62
ClothConfig 8.2.88
Faric API 0.72.0
GuardVillager 1.0.16
Appeals to work fine.

**Comment by jefflima1** [comment]
I have the same problem, any solution for this? I tried with version 1.19.4 Fabric

**Comment by T3aEnjoyer** [comment]
> It seems need specific version of Architectury mod for my instance to launch successfully. Architectury 6.4.62 ClothConfig 8.2.88 Faric API 0.72.0 GuardVillager 1.0.16 Appeals to work fine, apparently 1.19.3 don't work.

no WAY the architectury thing worked

**Comment by mrsterner** [comment]
fixed in 1.0.19
