### ISSUE TITLE
Fabric 1.19.4 crash when launching Minecraft 

### ISSUE THREAD

**Issue by qtCherry** [mrsterner/GuardVillagers#61]
As the title says my Minecraft crashes when launching the game with Guard Villagers mod installed.

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'guardvillagers'!

[log.txt](https://github.com/mrsterner/GuardVillagers/files/11179466/log.txt)

**Comment by mrsterner** [comment]
You need midnightlib
