### ISSUE TITLE
Broken items issues

### ISSUE THREAD

**Issue by winderine** [mrsterner/GuardVillagers#64]
Minecraft 1.19.2
Fabric 0.14.19
Fabric API 0.76.0
MidnightLib Fabric 1.0.0
Guard Villagers 1.1.2

When an unenchanted iron sword or crossbow runs out of durability, a new weapon is often duped into the offhand but cannot be used. A crossbow-guard with a crossbow in the wrong hand will track enemies with the crossbow but cannot load it. It's impossible to tell if a sword-guard has their weapon in the wrong hand unless you verified their handedness before - some guards are lefties - but sword-guard with the weapon in the wrong hand will punch instead of hitting with the sword.

In the inventory, shift-clicking on a weapon loads it into the offhand slot, possibly explaining the previous.

When iron armor runs out of durability, it is removed from the equipped items of the guard but not from the external appearance. the armor bar is decreased properly, but this means you cannot be certain that armor is missing unless you check the inventory.

**Comment by mrsterner** [comment]
Ah well thats annoying, not sure why it happens but i dont have time to check it out right now
