### ISSUE TITLE
Guards not Attacking

### ISSUE THREAD

**Issue by StealthMeister1** [mrsterner/GuardVillagers#68]
Guards will not attack any mob that isn't a zombie. I checked the config and the attackallmobs is set to true. I even deleted and retyped it to be sure. I don't know what to do.

**Comment by Poke097** [comment]
> Guards will not attack any mob that isn't a zombie. I checked the config and the attackallmobs is set to true. I even deleted and retyped it to be sure. I don't know what to do.

Try doing a search of maybe another mod causing this issue?

**Comment by StealthMeister1** [comment]
> > Guards will not attack any mob that isn't a zombie. I checked the config and the attackallmobs is set to true. I even deleted and retyped it to be sure. I don't know what to do.
> 
> Try doing a search of maybe another mod causing this issue?

What would I be searching for?

The only other 
![mods 5_10_2023 7_38_21 AM](https://github.com/mrsterner/GuardVillagers/assets/12484573/031f7785-55c9-4a51-b177-1671cd0bbd30)
mods I run are these. Mostly just structure generation replacements, maps, libraries, and sodium.

**Comment by StealthMeister1** [comment]
Does no one have an answer for this?

**Comment by StealthMeister1** [comment]
Still nothing? Wow.

**Comment by Poke097** [comment]
Maybe instead of commenting on here repeatedly, go to their discord and ask directly

**Comment by Poke097** [comment]
They have a server for their mods

**Comment by SolacianAllie** [comment]
Having the same issue, I do not have any mods that could conflict with this one to cause such behavior, It appears to be an issue with the mod, I would recommend somebody tests this
