### ISSUE TITLE
Gear despawn creative

### ISSUE THREAD

**Issue by VoidLock92** [mrsterner/GuardVillagers#7]
In creative mode guards items from their inventory will despawn when opening their inventory for the first time, but this does not happen when in survival mode.

**Comment by mrsterner** [comment]
Dont be in creative lol

**Comment by VoidLock92** [comment]
So if I want to use this and setup a village for players or a town outpost... I need to leave creative every single time just to change their equipment? Then change my gamemode back to continue working?

**Comment by mrsterner** [comment]
Yes, because i have no idea whats causing it
