### ISSUE TITLE
Guard menu "follow" and "stay" buttons don't work on dedicated servers

### ISSUE THREAD

**Issue by FishCells** [mrsterner/GuardVillagers#70]
Clicking on the "follow" or "stay put" buttons on guard menu does nothing while on a dedicated server. The buttons will remain X'd out.

Using a single player world the guard functions as expected. 

Minecraft version: 1.19.2
Guard Villagers version: 1.1.2

**Comment by thebigsleepjoe** [comment]
I have encountered the same problem. It's disappointing because one of the reasons I was interested in this mod was the ability to have a group of NPC guards protect me from my friends, lol.
