### ISSUE TITLE
Сrash on 1.20 of Minecraft fabric.

### ISSUE THREAD

**Issue by Pan-Etsu** [mrsterner/GuardVillagers#75]
Don`t work on version 1.20 of Minecraft fabric.
The following message appears:

![image](https://github.com/mrsterner/GuardVillagers/assets/132110408/caa45f88-d117-4279-b034-dd8c93c104a6)

I am using the following mods:

![image](https://github.com/mrsterner/GuardVillagers/assets/132110408/78c2d193-57d2-47fd-96f5-0f5798d7f1f7)

**Comment by mrsterner** [comment]
Get midnightlib
