### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by CyberSteve777** [mrsterner/GuardVillagers#82]
https://mclo.gs/ne7halT

**Comment by Fade-Alchemist** [comment]
Can confirm, the current version guardvillagers-2.0.6-1.19.2.jar is broken.
[crash-2023-08-06_14.32.38-client.txt](https://github.com/mrsterner/GuardVillagers/files/12271368/crash-2023-08-06_14.32.38-client.txt)

**Comment by mrsterner** [comment]
fixed in 2.0.7
