### ISSUE TITLE
1.20.1 Crash - Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [mrsterner/GuardVillagers#83]
Game version: 1.20.1 (Fabric)
Mod version: guardvillagers-2.0.6-1.20.1.jar

Happens randomly when cruising around in the world, near villages.
[crash-2023-08-07_10.48.55-server.txt](https://github.com/mrsterner/GuardVillagers/files/12274129/crash-2023-08-07_10.48.55-server.txt)

**Comment by mrsterner** [comment]
Hmm, I thought i fixed that, ill check it out this week
