### ISSUE TITLE
Crash when starting server 1.20.1

### ISSUE THREAD

**Issue by ForionOG** [mrsterner/GuardVillagers#84]
Mod version: guardvillagers-2.0.6-1.20.1.jar Fabric
Happens when starting server everything gets loaded and after the reload when loading is done it crashes.
[crash-2023-08-09_19.07.13-server.txt](https://github.com/mrsterner/GuardVillagers/files/12305210/crash-2023-08-09_19.07.13-server.txt)

**Comment by ForionOG** [comment]
also I just updated to 1.20.1 same world etc but since it wont start the server

**Comment by mrsterner** [comment]
Villagernames is causing the crash
