### ISSUE TITLE
Netty pipeline exception server spam

### ISSUE THREAD

**Issue by DadoIrie** [mrsterner/GuardVillagers#85]
Getting a quite frequent spam server side:
```
Exception occurred in netty pipeline
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
```
![image](https://github.com/mrsterner/GuardVillagers/assets/61109153/d3521fae-73a4-483d-a6af-ae59c3d5ad27)

It's definitely coming from GuardVillagers, because without it it doesn't happen - also not feeling comfortable filtering this out with a mod which suppresses targeted console outputs and also leaving it does unnecessarily grow the log file

**Comment by mrsterner** [comment]
idk what this is

**Comment by DadoIrie** [comment]
I checked the debug.log, but also sadly doesn't say more -.-

**Comment by mrsterner** [comment]
Alright

**Comment by DadoIrie** [comment]
so no further investigation regarding that issue?

**Comment by mrsterner** [comment]
Exactly

**Comment by mar1nho** [comment]
just came from the future to say that this error still occurs

**Comment by DadoIrie** [comment]
dev is not interested into fixing it and therefore the issue is closed

**Comment by mar1nho** [comment]
i know but i saw posts since 2017 and the problem is never solved some say its firewall issues but idk
