### ISSUE TITLE
1.20.1 The game collapsed

### ISSUE THREAD

**Issue by Xliecc** [mrsterner/GuardVillagers#86]
I'm playing the fabric version of 1.20.1 and every time I load the village, my game crashes
[Error reporting-15-8-2023_下午1.03.14.zip](https://github.com/mrsterner/GuardVillagers/files/12341409/Error.reporting-15-8-2023_.1.03.14.zip)

**Comment by mrsterner** [comment]
Im not opening a zip file, but i common issue is with the villagers names mod
