### ISSUE TITLE
MobBlackList not working?

### ISSUE THREAD

**Issue by JamesEakk** [mrsterner/GuardVillagers#9]
Hi,
I initially wanted to make them fight some mobs as Iron golem do (Most hostiles, no Enderman/Creeper).
but after i tried nothing seems to working.

1. I've changed `"AttackAllMobs": true,` , This works fine.
2. I leave 
`"MobBlackList": [
    "creeper"
  ]`
as is and testing it but the guards still killing them.
3.  so I tried changing the list to 
`"MobBlackList": [
    "minecraft:creeper"
  ]`
but not seems to work either. 

I used mod version 1.0.7 on Minecraft 1.18.1 single player world.

Did I do something wrong? Or It's just not working.
I have no clue.

Best Regards

**Comment by mrsterner** [comment]
Fixed in 1.0.9
